myapp/urls.py
# urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('register/', register_seller, name='register_seller'),
    path('validate_step/', validate_step, name='validate_step'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('api/countries/', load_countries, name='load_countries'),
    path('api/get_states/<int:country_id>/', load_states, name='load_states'),
    path('api/get_country_code/<int:country_id>/', get_country_code, name='get_country_code'),
    path('listing/create/', create_listing, name='create_listing'),
    path('ajax/load-states/', listing_load_states, name='listing_load_states'),
    path('listing/<slug:slug>/edit/', edit_listing, name='edit_listing'),
    path('listing/<slug:slug>/', listing_detail, name='listing_detail'),
    path('seller/listings/', seller_listings, name='seller_listings'),
    path('listings/', all_listings, name='all_listings'),
    path('country-autocomplete/', country_autocomplete, name='country_autocomplete'),
    path('state-autocomplete/', state_autocomplete, name='state_autocomplete'),
    path('buy-membership-listing/', buy_package_listing, name='buy_package_listing'),
    path('memberships/', public_packages, name='public_packages'),
    path('transactions/', transaction_history, name='transaction_history'),
    path('listing/<slug:slug>/submit_message/', submit_message, name='submit_message_with_slug'),
    path('seller/submit_message/', submit_message, name='submit_message_without_slug'),
    path('login/', login_user, name='login_user'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('dashboard/', dashboard, name='dashboard'),
    path('update-profile/', update_profile, name='update_profile'),
    path('change-password/', change_password, name='change_password'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('category/<slug:slug>/', category_detail, name='category_detail'),
    path('cancel-auto-renew/', cancel_auto_renew, name='cancel_auto_renew'),
    path('seller/messages/', seller_messages, name='seller_messages'),
    path('seller/messages/<int:message_id>/', message_detail, name='message_detail'),
    path('seller/<int:seller_id>/', seller_profile, name='seller_profile'),
    path('remove_payment_method/', remove_payment_method, name='remove_payment_method'),
    path('add-payment-method/', AddPaymentMethodView.as_view(), name='add_payment_method'),
    #new
    path('contact-us/', ContactUsView.as_view(), name='contact_us'),
    path('faqs/', faq_list, name='faq_list'),
    path('page/<slug:slug>/', page_detail, name='page_detail'),
    
    # Password reset URLs
    path('password-reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
]

myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from myapp.views import form_field_setting_changelist

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/formfieldsetting/', form_field_setting_changelist, name='formfieldsetting_changelist'),
    path('', include('myapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.forms import modelformset_factory
from tinymce.widgets import TinyMCE
import re
from .models import *

class LoginForm(forms.Form):
    username = forms.CharField(max_length=255)
    password = forms.CharField(widget=forms.PasswordInput())

class SellerRegistrationForm(forms.ModelForm):
    username = forms.CharField(max_length=255)
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    company_name = forms.CharField(max_length=255)
    country = forms.ModelChoiceField(queryset=Country.objects.all(), required=True)
    state = forms.ModelChoiceField(queryset=Region.objects.none(), required=False)
    city = forms.CharField(max_length=255, required=True)
    mobile_number = forms.CharField(max_length=20, required=False)
    company_address = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Company Address'}))
    company_phone_number = forms.CharField(
        max_length=20,
        validators=[RegexValidator(
            regex=r'^\+?1?\d{10}$',
            message="Invalid Phone Number"
        )]
    )
    first_name = forms.CharField(max_length=255)
    last_name = forms.CharField(max_length=255)

    class Meta:
        model = Seller
        fields = [
            'username', 'email', 'password', 'confirm_password', 'company_name', 'company_address',
            'country', 'state', 'city', 'company_phone_number', 'mobile_number',
            'first_name', 'last_name'
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                if country_id in [Country.objects.get(code='US').id, Country.objects.get(code='CA').id]:
                    self.fields['state'].required = True
                    self.fields['state'].queryset = Region.objects.filter(country_id=country_id).order_by('name')
                else:
                    self.fields['state'].required = False
                    self.fields['state'].queryset = Region.objects.none()
            except (ValueError, TypeError):
                pass
        elif self.instance.pk and self.instance.country:
            if self.instance.country.code in ['US', 'CA']:
                self.fields['state'].required = True
                self.fields['state'].queryset = Region.objects.filter(country=self.instance.country).order_by('name')
            else:
                self.fields['state'].required = False
                self.fields['state'].queryset = Region.objects.none()

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")
        country = cleaned_data.get("country")
        state = cleaned_data.get("state")

        if password != confirm_password:
            self.add_error('confirm_password', "Password and Confirm Password do not match")

        if country and country.code in ['US', 'CA'] and not state:
            self.add_error('state', "This field is required for US and Canada.")

        return cleaned_data
    
    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("This username is already taken.")
        return username

    def clean_company_phone_number(self):
        phone_number = self.cleaned_data.get('company_phone_number')
        if Seller.objects.filter(company_phone_number=phone_number).exists():
            raise forms.ValidationError("This phone number is already in use.")
        return phone_number

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("This email is already registered.")
        return email

    '''def clean_company_name(self):
        company_name = self.cleaned_data.get('company_name')
        if Seller.objects.filter(company_name=company_name).exists():
            raise forms.ValidationError("This company name is already registered.")
        return company_name'''

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if len(password) < 8:
            raise forms.ValidationError("Password must be at least 8 characters long.")
        if not re.search(r'[A-Z]', password):
            raise forms.ValidationError("Password must contain at least one uppercase letter.")
        if not re.search(r'[a-z]', password):
            raise forms.ValidationError("Password must contain at least one lowercase letter.")
        if not re.search(r'\d', password):
            raise forms.ValidationError("Password must contain at least one digit.")
        if not re.search(r'[!@#$%^&*(),.?":{}|<>]', password):
            raise forms.ValidationError("Password must contain at least one special character.")
        return password

class ListingForm(forms.ModelForm):
    thumbnail_image = forms.ImageField(required=False)
    project_country = forms.ModelChoiceField(queryset=Country.objects.all(), required=True)
    project_state = forms.ModelChoiceField(queryset=Region.objects.none(), required=False)
    project_city = forms.CharField(max_length=255, required=False)
    categories = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )
    project_description = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))
    remarks = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}), required=False)
    buyer_protections = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}), required=False)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        is_creation = kwargs.pop('is_creation', False)
        super(ListingForm, self).__init__(*args, **kwargs)

        if self.user:
            seller = self.user.seller
            if seller.featured_post_count == 0:
                self.fields['is_featured'].disabled = True

        if 'project_country' in self.data:
            try:
                country_id = int(self.data.get('project_country'))
                if country_id in [Country.objects.get(code='US').id, Country.objects.get(code='CA').id]:
                    self.fields['project_state'].queryset = Region.objects.filter(country_id=country_id).order_by('name')
                else:
                    self.fields['project_state'].queryset = Region.objects.none()
            except (ValueError, TypeError):
                pass
        elif self.instance.pk and self.instance.project_country:
            if self.instance.project_country.code in ['US', 'CA']:
                self.fields['project_state'].queryset = Region.objects.filter(country=self.instance.project_country).order_by('name')
            else:
                self.fields['project_state'].queryset = Region.objects.none()

        if is_creation:
            self.fields['status'].required = False
            self.fields['status'].initial = 'inactive'
            self.fields['status'].widget = forms.HiddenInput()
        else:
            self.fields['status'].widget = forms.Select(choices=Listing.STATUS_CHOICES)

        form_name = self.__class__.__name__
        field_settings = FormFieldSetting.objects.filter(form_name=form_name).order_by('order')

        for setting in field_settings:
            if setting.field_name in self.fields:
                self.fields[setting.field_name].label = setting.label

        ordered_fields = [setting.field_name for setting in field_settings]

        if is_creation and seller.featured_post_count > 0:
            ordered_fields.insert(0, 'is_featured')
        elif not is_creation and self.instance.is_featured:
            ordered_fields.insert(0, 'is_featured')

        self.order_fields(ordered_fields)

    def clean_sales_price(self):
        sales_price = self.cleaned_data.get('sales_price')
        if sales_price <= 0:
            raise forms.ValidationError("Sales price must be greater than zero.")
        return sales_price

    class Meta:
        model = Listing
        fields = [
            'categories', 'project_ntp_date', 'project_cod_date', 'project_pto_date',
            'is_featured', 'project_name', 'project_description', 'contractor_name',
            'project_size', 'battery_storage', 'projected_annual_income', 'epc_name', 'current_annual_om_cost',
            'om_escalation_rate', 'sales_price', 'project_address', 'project_country', 'project_state', 'project_city',
            'lot_size', 'property_type', 'lease_term', 'current_lease_rate_per_acre', 'lease_escalation_rate',
            'project_status', 'tax_credit_type', 'total_tax_credit_percentage', 'remarks', 'buyer_protections',
            'latitude', 'longitude', 'thumbnail_image', 'status'
        ]
        labels = {
            'categories': 'Project Technology*',
            'project_ntp_date': 'Project NTP Date',
            'project_cod_date': 'Project COD Date',
            'project_pto_date': 'Project PTO Date',
            'is_featured': 'Featured',
            'project_name': 'Project Name*',
            'project_description': 'Project Description',
            'contractor_name': 'Contractor Name',
            'project_size': 'Project Size',
            'battery_storage': 'Battery Storage',
            'projected_annual_income': 'Projected Annual Income',
            'epc_name': 'EPC Name',
            'current_annual_om_cost': 'Current Annual O&M Cost',
            'om_escalation_rate': 'O&M Escalation Rate',
            'sales_price': 'Sales Price',

templates/buy_individual_listing.html
{% block title %}Buy Individual Listing{% endblock %}
{% block content %}
    <h2>Buy Individual Listing</h2>
    <form method="post" id="payment-form">
        {% csrf_token %}
        {{ form.as_p }}
        <div id="card-element">
            <!-- A Stripe Element will be inserted here. -->
        </div>
        <button type="submit">Buy Listing</button>
    </form>
    <script>
        var stripe = Stripe('{{ stripe_key }}');
        var elements = stripe.elements();
        var card = elements.create('card');
        card.mount('#card-element');

        var form = document.getElementById('payment-form');
        form.addEventListener('submit', function(event) {
            event.preventDefault();

            stripe.createToken(card).then(function(result) {
                if (result.error) {
                    // Inform the user if there was an error.
                    var errorElement = document.getElementById('card-errors');
                    errorElement.textContent = result.error.message;
                } else {
                    // Send the token to your server.
                    stripeTokenHandler(result.token);
                }
            });
        });

        function stripeTokenHandler(token) {
            var form = document.getElementById('payment-form');
            var hiddenInput = document.createElement('input');
            hiddenInput.setAttribute('type', 'hidden');
            hiddenInput.setAttribute('name', 'stripeToken');
            hiddenInput.setAttribute('value', token.id);
            form.appendChild(hiddenInput);

            form.submit();
        }
    </script>
{% endblock %}

templates/category_detail.html
{% extends 'base.html' %}

{% block title %}Category Detail{% endblock %}

{% load static %}

{% block content %}

<h1>Listings for Category: {{ category.name }}</h1>
    <p>{{ category.description }}</p>
    <ul>
        {% for listing in listings %}
            <li>
                <a href="{% url 'listing_detail' listing.id %}">{{ listing.title }}</a>
                <p>{{ listing.description }}</p>
                <p>Price: {{ listing.price }}</p>
            </li>
        {% endfor %}
    </ul>


{% endblock %}

templates/edit_listing.html
{% extends "base.html" %}
{% load form_filters %}
{% load static %}
{% block title %}Edit Listing - {{ form.instance.project_name }}{% endblock %}
{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'listing/styles.css' %}">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
<style>
    /* Popup Modal Styles */
    .modal {
        display: none; /* Hidden by default */
        position: fixed; /* Stay in place */
        z-index: 1050; /* Sit on top */
        left: 0;
        top: 0;
        width: 100%; /* Full width */
        height: 100%; /* Full height */
        overflow: hidden; /* Disable scroll if needed */
        background-color: rgba(0,0,0,0.5); /* Black w/ opacity */
    }

    .modal-dialog {
        position: relative;
        margin: auto;
        top: 50%;
        transform: translateY(-50%);
        width: 100%;
        max-width: 500px;
    }

    .modal-content {
        background-color: #fff;
        padding: 20px;
        border: 1px solid #888;
        border-radius: 8px;
        box-shadow: 0 5px 15px rgba(0,0,0,0.3);
        text-align: center;
    }

    .modal-header, .modal-footer {
        padding: 4px;
    }

    .modal-header {
        border-bottom: 1px solid #e5e5e5;
    }

    .modal-footer {
        border-top: 1px solid #e5e5e5;
    }

    .modal-title {
        text-align: center;
        font-size: 18px;
    }

    .modal-body {
        text-align: center;
        margin: 15px 0;
    }

    .btn-primary, .btn-secondary {
        background-color: #64C2DB;
        border-color: #64C2DB;
        color: white;
        padding: 10px;
        border-radius: 8px;
        width: 100%;
        border: 0px;
        margin-top: 10px;
        cursor: pointer;
    }

    .btn-primary:hover, .btn-secondary:hover {
        background-color: #4fa6bd;
        border-color: #4fa6bd;
    }

    .jconfirm {
        z-index: 10000 !important;
    }
    .jconfirm-box {
        margin: 0 auto;
        top: 50% !important;
    }

    .jc-bs3-row.row.justify-content-md-center.justify-content-sm-center.justify-content-xs-center.justify-content-lg-center{
        margin: 0 auto;
    }
</style>
{% endblock %}
{% block content %}
<div class="listing-create-container">
    <h2>Edit Listing - {{ form.instance.project_name }} </h2>
    <form id="listing-edit-form" method="post" enctype="multipart/form-data" class="listing-create-form">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div id="form-content">
            {% for field_name in field_order %}
                {% with form|get_field:field_name as field %}
                <div class="listing-create-form-group {% if field_name in 'lease_term current_lease_rate_per_acre lease_escalation_rate' %}lease-field{% endif %}{% if field_name == 'battery_storage' %} battery-storage{% endif %}" {% if field_name == 'battery_storage' %}style="display: none;"{% endif %}>
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        {% if field.help_text %}
                            <small class="form-text text-muted">{{ field.help_text }}</small>
                        {% endif %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback">{{ error }}</div>
                        {% endfor %}
                    </div>
                {% endwith %}
            {% endfor %}
        </div>

        <h3>Existing Images</h3>
        {% for image in existing_images %}
            <div class="listing-create-form-group">
                <img src="{{ image.image.url }}" alt="Image" width="100">
                <label>
                    <input type="checkbox" name="delete_images" value="{{ image.id }}">
                    Delete
                </label>
            </div>
        {% endfor %}

        <h3>Listing Images</h3>
        <div class="listing-create-form-group">
            <label for="id_images">Upload Images</label>
            <input type="file" id="id_images" name="images" multiple>
            <small class="form-text text-muted">You can select multiple images or drag and drop them here.</small>
        </div>

        <button id="submit-button" type="submit" class="listing-create-btn btn btn-primary">Update Listing</button>
    </form>
</div>

<!-- Popup Message -->
<div id="success-popup" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="popup-title"></h5>
            </div>
            <div class="modal-body">
                <p id="popup-message"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="popup-close-btn">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- Confirmation Message -->
<div id="confirmation-popup" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Confirmation</h5>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to set the listing to inactive? Activating the listing will cost a new listing count.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="confirm-yes-btn">Yes</button>
                <button type="button" class="btn btn-secondary" id="confirm-no-btn">No</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block extra_js %}
<script src="{% static 'tinymce/js/tinymce/tinymce.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
<script>
    function initializeTinyMCE() {
        tinymce.remove();
        tinymce.init({
            selector: 'textarea',
            plugins: 'lists link',
            menubar: false,
            toolbar: 'bold italic underline | bullist numlist | link',
            height: 300,
            branding: false,
            forced_root_block: 'p',
            force_p_newlines: true,
            force_br_newlines: false,
            content_css: false,
            content_style: "body { font-family:Helvetica,Arial,sans-serif; font-size:14px }",
            valid_elements: 'p,b,strong,i,em,a[href],ul,ol,li',
            invalid_elements: 'script,iframe,object,embed',
            license_key: 'gpl'
        });
    }

    function toggleLeaseFields() {
        var leaseFields = document.querySelectorAll('.lease-field');
        var propertyTypeElement = document.getElementById('id_property_type');
        if (propertyTypeElement) {
            var propertyType = propertyTypeElement.value;
            leaseFields.forEach(function (fieldElement) {
                if (propertyType === 'lease') {
                    fieldElement.style.display = 'block';
                } else {
                    fieldElement.style.display = 'none';
                }
            });
        }
    }

    function toggleBatteryStorage() {
        var batteryField = document.querySelector('.battery-storage');
        if (batteryField) {
            var selectedCategories = Array.from(document.querySelectorAll('#id_categories input[type="checkbox"]:checked')).map(cb => cb.labels[0].textContent.trim());
            if (selectedCategories.includes('BESS')) {
                batteryField.style.display = 'block';
            } else {
                batteryField.style.display = 'none';
            }
        }
    }

    function handleStateFieldLogic() {
        var countryId = $('#id_project_country').val();
        var stateFieldWrapper = $('.listing-create-form-group:has(#id_project_state)');

        if (countryId === "{{ 230 }}" || countryId === "{{ 39 }}") {
            stateFieldWrapper.show();
            var url = "{% url 'listing_load_states' %}";
            $.ajax({
                url: url,
                data: {
                    'country_id': countryId
                },
                success: function (data) {
                    var stateSelect = $('#id_project_state');
                    stateSelect.html('<option value="">Select a state</option>');
                    $.each(data, function (key, value) {
                        stateSelect.append('<option value="' + value.id + '">' + value.name + '</option>');
                    });
                    stateSelect.val('{{ form.instance.project_state.id }}');
                }
            });
        } else {
            stateFieldWrapper.hide();
            $('#id_project_state').html('<option value="">Not applicable</option>');
        }
    }

    function scrollToFirstError() {
        var firstErrorElement = $('.is-invalid').first();
        if (firstErrorElement.length) {
            $('html, body').animate({
                scrollTop: firstErrorElement.offset().top - 100
            }, 1000);
        }
    }

    function reinitializeFormElements() {
        initializeTinyMCE();
        toggleLeaseFields();
        toggleBatteryStorage();
        handleStateFieldLogic();
    }

    $(document).ready(function() {
        document.getElementById('id_property_type').addEventListener('change', toggleLeaseFields);
        $('#id_categories').change(toggleBatteryStorage);

        toggleLeaseFields();
        toggleBatteryStorage();

        $('#id_project_country').change(handleStateFieldLogic);

        var countrySelect = document.getElementById('id_project_country');
        var selectedCountry = countrySelect.value;
        if (selectedCountry) {
            $(countrySelect).trigger('change');
        }

        $('#id_project_country').val('{{ form.instance.project_country.id }}').trigger('change');

        function submitForm() {
            var formData = new FormData($('#listing-edit-form')[0]);

            $('#submit-button').prop('disabled', true).html('Updating...');

            $.ajax({
                type: 'POST',
                url: '{% url "edit_listing" form.instance.slug %}',
                data: formData,
                processData: false,
                contentType: false,
                success: function(response) {
                    if (response.success) {
                        $('#popup-title').text('Success');
                        $('#popup-message').text(response.message);
                        $('#success-popup').show();
                    } else {
                        $('#popup-title').text(response.message_type);
                        $('#popup-message').text(response.message);
                        $('#success-popup').show();
                    }
                },
                error: function(xhr) {
                    console.log("Form submission failed:", xhr.responseJSON);
                    $('#form-content').html(xhr.responseJSON.form_html || '');
                    var errors = xhr.responseJSON.errors || {};
                    var firstErrorElement = null;

                    $.each(errors, function(field, messages) {
                        var fieldElement = $('[name="' + field + '"]').closest('.listing-create-form-group');
                        if (fieldElement.length) {
                            fieldElement.addClass('is-invalid');
                            fieldElement.find('.invalid-feedback').html(messages.join(', '));
                            if (!firstErrorElement) {
                                firstErrorElement = fieldElement[0];
                            }
                        } else {
                            if (!firstErrorElement && field === '__all__') {
                                var nonFieldErrors = messages.join(', ');
                                $('#form-content').prepend('<div class="alert alert-danger non-field-error">' + nonFieldErrors + '</div>');
                                firstErrorElement = $('.non-field-error')[0];
                            }
                        }
                    });

                    $.alert({
                        title: 'Error',
                        content: 'Please fix the highlighted errors and try again.',
                        onClose: function () {
                            setTimeout(function() {
                                scrollToFirstError();
                                reinitializeFormElements();
                            }, 0);
                        }
                    });

                    $('#submit-button').prop('disabled', false).html('Update Listing');
                }
            });
        }

        var formSubmitting = false;

        $('#listing-edit-form').submit(function(e) {
            e.preventDefault();
            tinymce.triggerSave();

            if (!formSubmitting && $('#id_status').val() === 'inactive') {
                $('#confirmation-popup').show();
                return;
            }

            formSubmitting = true;
            submitForm();
        });

        $('#popup-close-btn').click(function() {
            $('#success-popup').hide();
            location.reload();
        });

        $('#confirm-yes-btn').click(function() {
            $('#confirmation-popup').hide();
            formSubmitting = true;
            submitForm();
        });

        $('#confirm-no-btn').click(function() {
            $('#confirmation-popup').hide();
        });

        reinitializeFormElements();
    });
</script>

{% endblock %}

templates/edit_listing_form.html
{% load form_filters %}
{% for field_name in field_order %}
    {% with form|get_field:field_name as field %}
    <div class="listing-create-form-group {% if field_name in 'lease_term current_lease_rate_per_acre lease_escalation_rate' %}lease-field{% endif %}{% if field_name == 'battery_storage' %} battery-storage{% endif %}" {% if field_name == 'battery_storage' %}style="display: none;"{% endif %}>
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
            {% endif %}
            <div class="invalid-feedback">{{ field.errors }}</div>
        </div>
    {% endwith %}
{% endfor %}

templates/page_detail.html
{% extends "base.html" %}
{% block title %} {{ page.title }} {% endblock %}
{% block extra_css %}
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/choices.js/public/assets/styles/choices.min.css" />
<style>
  .content-wrapper {
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: flex-start; /* Left align */
      padding: 40px;
      box-sizing: border-box;
  }

  .content-wrapper h2 {
      margin-bottom: 20px;
      font-size: 2em; /* Ensure the title stands out */
  }

  .content {
      width: 100%;
  }

  /* Ensure proper mobile optimization */
  @media (max-width: 768px) {
      .content-wrapper {
          padding: 10px;
      }
  }
</style>
{% endblock %}
{% block content %}
  <div class="content-wrapper">
    <h2>{{ page.title }}</h2>
    <div class="content">{{ page.content|safe }}</div>
  </div>
{% endblock %}
{% block extra_js %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/choices.js/public/assets/scripts/choices.min.js"></script>
{% endblock %}